/**
 * IR v1 → After Effects ExtendScript (.jsx) 构建脚本。
 *
 * 生成的脚本在 AE 里跑一遍即重建合成：canvas 尺寸/时长/fps、逐层固态/文本/占位层、
 * pos/scale/rotation/opacity 关键帧 + temporal ease 尽力映射；fx 已知 matchName 的生成
 * applyEffect 调用，未知的写 TODO 注释。
 *
 * 反向参考：ae_export_kit/dump_aep.jsx（本文件即其"读"操作的"写"镜像）。
 *
 * MAD 扩展（add-tool-mad，全部 opt-in——不传 opts 时输出与迁入前逐字节一致，见 ir-convert-library spec）：
 *   - opts.header：产物 header 可配置（默认「仅供学习研究」不变）
 *   - opts.footage：素材注入（layerId → footage 路径 + srcOffset），一窗口一素材共用、缺文件回退灰固态
 *   - opts.bakeOps：时序算子烘焙（shake/pulsate/oscillate/zoom/flicker → 关键帧，见 bake_ops.ts）
 *   - madJsx()：母合成拼接（子合成完整铺 + 三属性裁窗 + BGM 入轨 + beat marker）
 */
import { bakeLayerOps, sampleTrack, TIME_DOMAIN_OPS } from "./bake_ops";
import type { ExportResult, IRAnim, IRFx, IRLayer, IRProject } from "./types";
import { fontPx, mergeChannelTracks, num, parseCssColor, parseCubicBezier } from "./types";

const HEADER = `// 由技法图鉴重建生成,仅供学习研究;素材为占位,请替换
// Generated by gitruck-creation IR->JSX converter. For study only; placeholder footage, replace before use.
// 用法: AE 菜单 文件>脚本>运行脚本文件 选择本文件（AE 2020+ 建议）`;

/** IR fx op → AE 原生特效 matchName（已验证的常识映射；无把握的一律进 TODO 注释） */
const FX_MATCHNAME: Record<string, string> = {
  glow: "ADBE Glo2", // Glow
  blur: "ADBE Gaussian Blur 2", // Gaussian Blur
  dirBlur: "ADBE Motion Blur", // Directional Blur
  turbulence: "ADBE Turbulent Displace",
  tile: "ADBE Tile", // Motion Tile
  dropShadow: "ADBE Drop Shadow",
  invert: "ADBE Invert",
  wipe: "ADBE Linear Wipe",
  bulge: "ADBE Bulge",
  noise: "ADBE Noise",
  fill: "ADBE Fill",
  vignette: "ADBE Vignette", // Lumetri 之外的独立 Vignette（较新 AE），失败会被 try/catch 吞掉
  colorAdjust: "ADBE Brightness & Contrast 2",
};

function esc(s: string): string {
  return String(s)
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\r/g, "\\r")
    .replace(/\n/g, "\\n")
    .replace(/\t/g, "\\t")
    // 行分隔符会截断 ExtendScript 字符串字面量（U+2028/U+2029，用 fromCharCode 避免源码里出现裸分隔符）
    .replace(new RegExp(String.fromCharCode(0x2028), "g"), "\\u2028")
    .replace(new RegExp(String.fromCharCode(0x2029), "g"), "\\u2029");
}

function r3(v: number): number {
  return Math.round(v * 1000) / 1000;
}

function colorArr(css: string | undefined, fallback: [number, number, number]): [number, number, number] {
  const c = parseCssColor(css);
  if (!c) return fallback;
  return [r3(c[0] / 255), r3(c[1] / 255), r3(c[2] / 255)];
}

/**
 * cubic-bezier → AE temporal ease 尽力映射：
 * 出向 influence ≈ x1*100，入向 influence ≈ (1-x2)*100（clamp 到 AE 允许的 [0.1,100]），speed=0。
 * 这是常见的"平滑进出"近似——精确速度曲线不可逆推，保形不保速。
 */
function easeInfluence(e: string | null | undefined): { out: number; inn: number } | null {
  const cb = parseCubicBezier(e);
  if (!cb) return null;
  const clamp = (v: number) => Math.min(100, Math.max(0.1, v));
  return { out: clamp(cb[0] * 100 || 33), inn: clamp((1 - cb[2]) * 100 || 33) };
}

/** MAD 素材注入映射：layerId → footage 路径 + 取段偏移（秒）。 */
export interface FootageMap {
  [layerId: string]: { path: string; srcOffset?: number };
}

export interface JsxOpts {
  /** 产物 header 文案（默认「仅供学习研究」口径不变）。 */
  header?: string;
  /** 素材注入：layerId → footage（一窗口一素材由调用侧映射保证：同素材多 slot 用同 path 不同 srcOffset）。 */
  footage?: FootageMap;
  /** 时序算子烘焙开关（默认 false：保持现 TODO 注释路径，零回归）。 */
  bakeOps?: boolean;
  /** 内部：发射进指定合成变量（madJsx 子合成用），缺省 "comp"。 */
  compVar?: string;
}

interface Ctx {
  lines: string[];
  warnings: string[];
  layerSeq: number;
  compVar: string;
  footage: FootageMap;
  bakeOps: boolean;
  /** footage 路径 → 已 import 的 JSX 变量名（每路径仅 importFile 一次、复用）。 */
  footageVars: Map<string, string>;
}

/** 生成一条 setValueAtTime 序列 + ease */
function emitKeys(
  ctx: Ctx,
  propExpr: string,
  keys: { t: number; value: string; e?: string | null }[],
): void {
  if (keys.length === 0) return;
  const L = ctx.lines;
  L.push(`  try {`);
  L.push(`    var p = ${propExpr};`);
  for (const k of keys) {
    L.push(`    p.setValueAtTime(${r3(k.t)}, ${k.value});`);
  }
  // temporal ease（逐 key 尽力）
  keys.forEach((k, i) => {
    const inf = easeInfluence(k.e);
    if (!inf) return;
    L.push(`    try {`);
    L.push(`      var dim = 1; try { dim = p.value.length || 1; } catch (e) { dim = 1; }`);
    L.push(`      var eo = [], ei = [];`);
    L.push(
      `      for (var d = 0; d < Math.min(dim, 3); d++) { eo.push(new KeyframeEase(0, ${r3(inf.out)})); ei.push(new KeyframeEase(0, ${r3(inf.inn)})); }`,
    );
    L.push(`      p.setTemporalEaseAtKey(${i + 1}, ei, eo);`);
    L.push(`    } catch (e) {}`);
  });
  L.push(`  } catch (e) {}`);
}

function fxComment(fx: IRFx): string {
  const params = Object.keys(fx)
    .filter((k) => !["op", "src", "tracks"].includes(k))
    .map((k) => `${k}=${JSON.stringify((fx as Record<string, unknown>)[k])}`)
    .join(" ");
  const tracks = fx.tracks ? ` tracks:[${Object.keys(fx.tracks).join(",")}]` : "";
  return `${fx.op}${fx.src ? ` (原特效: ${fx.src})` : ""}${params ? " " + params : ""}${tracks}`;
}

function emitEffects(ctx: Ctx, layerVar: string, fxList: IRFx[] | undefined): void {
  if (!fxList || fxList.length === 0) return;
  const L = ctx.lines;
  L.push(`  // —— 特效（原工程特效清单，已知 matchName 自动 applyEffect，其余 TODO 手动补）——`);
  for (const fx of fxList) {
    const mn = FX_MATCHNAME[fx.op];
    // 烘焙开时时序算子由 emitBakedOps 承接（不再输出 TODO、不 addProperty），跳过
    if (ctx.bakeOps && TIME_DOMAIN_OPS.has(fx.op)) continue;
    if (mn && !TIME_DOMAIN_OPS.has(fx.op)) {
      L.push(`  // fx: ${esc(fxComment(fx))}`);
      L.push(`  try { ${layerVar}.property("ADBE Effect Parade").addProperty("${mn}"); } catch (e) {}`);
    } else if (TIME_DOMAIN_OPS.has(fx.op)) {
      L.push(`  // TODO fx(时序算子,请用表达式或关键帧手动复现): ${esc(fxComment(fx))}`);
      ctx.warnings.push(`jsx: 时序算子 ${fx.op} 未自动铺帧（已写 TODO 注释）`);
    } else {
      L.push(`  // TODO fx(无对应 AE 原生 matchName): ${esc(fxComment(fx))}`);
      ctx.warnings.push(`jsx: 未映射特效 ${fx.op}（已写 TODO 注释）`);
    }
  }
}

// ---------------------------------------------------------------- 烘焙轨合并（bakeOps 时）

/** 一条待发射的绝对关键帧：value 已格式化为 JSX 字面量。 */
interface AbsKey {
  t: number;
  value: string;
  e?: string | null;
}

/** 基轨采样：位置/缩放倍数（供窗界锚点用）。 */
function samplePos(anim: IRAnim, pos: [number, number], t: number): [number, number] {
  return [sampleTrack(anim.x, t, pos[0]), sampleTrack(anim.y, t, pos[1])];
}
function sampleScaleMul(anim: IRAnim, t: number): [number, number] {
  if (anim.scale?.length) {
    const s = sampleTrack(anim.scale, t, 1);
    return [s, s];
  }
  if (anim.sx?.length || anim.sy?.length) return [sampleTrack(anim.sx, t, 1), sampleTrack(anim.sy, t, 1)];
  return [1, 1];
}

/**
 * 合并基轨关键帧与烘焙轨：窗内基轨帧抑制、baked 帧铺入、窗界补基轨锚点。
 * baseKeys 为已格式化的基轨帧（含 ease）；bakedKeys 为 baked 轨帧（线性，无 ease）。
 * windows 为各烘焙窗；layerIn/Out 用于锚点边界钳制。
 */
function mergeBaked(
  baseKeys: AbsKey[],
  bakedKeys: AbsKey[],
  windows: [number, number][],
  anchorAt: (t: number) => string,
  layerIn: number,
  layerOut: number,
): AbsKey[] {
  const inWindow = (t: number): boolean => {
    for (const w of windows) if (t > w[0] + 1e-6 && t < w[1] - 1e-6) return true;
    return false;
  };
  const out: AbsKey[] = [];
  // 窗外基轨帧保留（含 ease）
  for (const k of baseKeys) if (!inWindow(k.t)) out.push(k);
  // 窗界基轨锚点（退出后回落基轨，避免停在算子末值）
  const EPS = 0.033; // ~1 帧@30fps
  for (const w of windows) {
    if (w[1] < layerOut - EPS) {
      const at = Math.min(w[1] + EPS, layerOut);
      out.push({ t: at, value: anchorAt(at), e: null });
    }
    if (w[0] > layerIn + EPS) {
      const at = Math.max(w[0] - EPS, layerIn);
      out.push({ t: at, value: anchorAt(at), e: null });
    }
  }
  // baked 帧
  out.push(...bakedKeys);
  // 排序 + 去重（同刻取后者，优先 baked）
  out.sort((a, b) => a.t - b.t);
  const ded: AbsKey[] = [];
  for (const k of out) {
    if (ded.length && Math.abs(k.t - ded[ded.length - 1].t) < 1e-6) ded[ded.length - 1] = k;
    else ded.push(k);
  }
  return ded;
}

/** 基轨 position 帧（x/y 合并、绝对 px）。 */
function positionBaseKeys(anim: IRAnim, pos: [number, number]): AbsKey[] {
  if (!(anim.x?.length || anim.y?.length)) return [];
  const merged = mergeChannelTracks(anim.x, anim.y, pos[0], pos[1]);
  return merged.map((k) => ({ t: k.t, value: `[${r3(k.a)}, ${r3(k.b)}]`, e: k.e }));
}

/** 基轨 scale 帧（→ 百分数；footage 乘 cover）。 */
function scaleBaseKeys(anim: IRAnim, coverExpr: string | null): AbsKey[] {
  const sc = (v: number): string => (coverExpr ? `${r3(v)}*${coverExpr}` : `${r3(v)}`);
  if (anim.scale?.length) {
    return anim.scale.map((k) => ({ t: k.t, value: `[${sc(num(k.v, 1) * 100)}, ${sc(num(k.v, 1) * 100)}]`, e: k.e }));
  }
  if (anim.sx?.length || anim.sy?.length) {
    const merged = mergeChannelTracks(anim.sx, anim.sy, 1, 1);
    return merged.map((k) => ({ t: k.t, value: `[${sc(k.a * 100)}, ${sc(k.b * 100)}]`, e: k.e }));
  }
  return [];
}

/** 烘焙轨发射（position/scale/rotation 合并进基轨；brightness→亮度对比度特效）。 */
function emitBakedOps(ctx: Ctx, ly: IRLayer, layerVar: string, tf: string, coverExpr: string | null): void {
  const { tracks, warnings } = bakeLayerOps(ly);
  for (const w of warnings) ctx.warnings.push(w);
  if (tracks.length === 0) return;
  const anim = ly.anim ?? {};
  const pos: [number, number] = [num(ly.pos?.[0], 0), num(ly.pos?.[1], 0)];
  const inn = num(ly.in, 0);
  const out = Math.max(inn + 0.01, num(ly.out, inn + 1));
  const sc = (v: number): string => (coverExpr ? `${r3(v)}*${coverExpr}` : `${r3(v)}`);

  // brightness（flicker）→ 亮度对比度特效参数轨
  const brights = tracks.filter((t) => t.prop === "brightness");
  if (brights.length) {
    ctx.lines.push(`  // fx: flicker → 亮度脉冲（ADBE Brightness & Contrast 2，避开 opacity 通道）`);
    ctx.lines.push(
      `  var flkFx = null; try { flkFx = ${layerVar}.property("ADBE Effect Parade").addProperty("ADBE Brightness & Contrast 2"); } catch (e) { flkFx = null; }`,
    );
    for (const bt of brights) {
      const keys = bt.times.map((t, i) => ({ t, value: `${r3(bt.values[i][0])}`, e: null }));
      emitKeys(ctx, `flkFx.property(1)`, keys);
    }
  }

  // position
  const posBaked = tracks.filter((t) => t.prop === "position");
  if (posBaked.length) {
    const baseKeys = positionBaseKeys(anim, pos);
    const bakedKeys: AbsKey[] = [];
    const windows: [number, number][] = [];
    for (const bt of posBaked) {
      windows.push(bt.window);
      for (let i = 0; i < bt.times.length; i++) {
        bakedKeys.push({ t: bt.times[i], value: `[${r3(bt.values[i][0])}, ${r3(bt.values[i][1])}]`, e: null });
      }
    }
    const merged = mergeBaked(
      baseKeys,
      bakedKeys,
      windows,
      (t) => {
        const [x, y] = samplePos(anim, pos, t);
        return `[${r3(x)}, ${r3(y)}]`;
      },
      inn,
      out,
    );
    emitKeys(ctx, `${tf}.property("ADBE Position")`, merged);
  }

  // scale（baked 值已为百分数；footage 乘 cover）
  const scaleBaked = tracks.filter((t) => t.prop === "scale");
  if (scaleBaked.length) {
    const baseKeys = scaleBaseKeys(anim, coverExpr);
    const bakedKeys: AbsKey[] = [];
    const windows: [number, number][] = [];
    for (const bt of scaleBaked) {
      windows.push(bt.window);
      for (let i = 0; i < bt.times.length; i++) {
        bakedKeys.push({ t: bt.times[i], value: `[${sc(bt.values[i][0])}, ${sc(bt.values[i][1])}]`, e: null });
      }
    }
    const merged = mergeBaked(
      baseKeys,
      bakedKeys,
      windows,
      (t) => {
        const [mx, my] = sampleScaleMul(anim, t);
        return `[${sc(mx * 100)}, ${sc(my * 100)}]`;
      },
      inn,
      out,
    );
    emitKeys(ctx, `${tf}.property("ADBE Scale")`, merged);
  }

  // rotation
  const rotBaked = tracks.filter((t) => t.prop === "rotation");
  if (rotBaked.length) {
    const baseKeys = (anim.rot ?? []).map((k) => ({ t: k.t, value: `${r3(num(k.v, 0))}`, e: k.e }));
    const bakedKeys: AbsKey[] = [];
    const windows: [number, number][] = [];
    for (const bt of rotBaked) {
      windows.push(bt.window);
      for (let i = 0; i < bt.times.length; i++) bakedKeys.push({ t: bt.times[i], value: `${r3(bt.values[i][0])}`, e: null });
    }
    const merged = mergeBaked(baseKeys, bakedKeys, windows, (t) => `${r3(sampleTrack(anim.rot, t, 0))}`, inn, out);
    emitKeys(ctx, `${tf}.property("ADBE Rotate Z")`, merged);
  }
}

/** 单层发射。parentNullVar: 所属 group 的 null 层变量名（无则 null） */
function emitLayer(ctx: Ctx, ir: IRProject, ly: IRLayer, parentNullVar: string | null): void {
  const L = ctx.lines;
  const cv = ctx.compVar;
  const c = ir.canvas;
  const id = ++ctx.layerSeq;
  const v = `ly${id}`;
  const inn = num(ly.in, 0);
  const out = Math.max(inn + 0.01, num(ly.out, c.duration));
  const px = num(ly.pos?.[0], c.w / 2);
  const py = num(ly.pos?.[1], c.h / 2);
  const name = esc(`${ly.id || "L" + id} [${ly.type}]`);

  L.push(``);
  L.push(`  // ---- 层 ${name} in=${r3(inn)} out=${r3(out)} ----`);

  if (ly.type === "group") {
    // 组 → null 层，子层挂其下（组通常是透明容器：null 摆在 [0,0]，子层用画布绝对坐标，
    // 组动画通过 null 关键帧整体带动；组自身 rot/scale 动画场景极罕见，不做）
    L.push(`  var ${v} = ${cv}.layers.addNull(${r3(c.duration)});`);
    L.push(`  ${v}.name = "${name}";`);
    L.push(`  ${v}.inPoint = ${r3(inn)}; ${v}.outPoint = ${r3(out)};`);
    L.push(`  ${v}.property("ADBE Transform Group").property("ADBE Anchor Point").setValue([0,0]);`);
    L.push(`  ${v}.property("ADBE Transform Group").property("ADBE Position").setValue([0,0]);`);
    if (parentNullVar) L.push(`  try { ${v}.parent = ${parentNullVar}; } catch (e) {}`);
    emitGroupAnim(ctx, v, ly);
    emitEffects(ctx, v, ly.fx);
    for (const child of ly.children ?? []) emitLayer(ctx, ir, child, v);
    return;
  }

  // MAD 素材注入：image/video 且 footage 映射命中 → footage 层（cover 缩放 + srcOffset 取段）
  let coverExpr: string | null = null;
  const footageHit = ly.type === "image" || ly.type === "video" ? ctx.footage[ly.id] : undefined;
  const fgVar = footageHit ? ctx.footageVars.get(footageHit.path) : undefined;

  if (footageHit && fgVar) {
    const slotW = Math.max(2, Math.round(num(ly.w, c.w)));
    const slotH = Math.max(2, Math.round(num(ly.h, c.h)));
    const srcOffset = num(footageHit.srcOffset, 0);
    const cvv = `cv${id}`;
    coverExpr = cvv;
    L.push(`  // 素材注入(${esc(String(ly.type))}): footage srcOffset=${r3(srcOffset)}`);
    L.push(`  var ${v} = null, ${cvv} = 1;`);
    L.push(`  if (${fgVar} != null) {`);
    L.push(`    try {`);
    L.push(`      ${v} = ${cv}.layers.add(${fgVar});`);
    L.push(`      var _fw = ${fgVar}.width || ${slotW}, _fh = ${fgVar}.height || ${slotH};`);
    L.push(`      ${cvv} = Math.max(${slotW} / _fw, ${slotH} / _fh);`);
    L.push(`      ${v}.startTime = ${r3(inn)} - ${r3(srcOffset)};`);
    L.push(`    } catch (e) { ${v} = null; }`);
    L.push(`  }`);
    L.push(`  if (${v} == null) {`);
    L.push(`    ${v} = ${cv}.layers.addSolid([0.35,0.35,0.4], "${name} [占位]", ${slotW}, ${slotH}, 1, ${r3(c.duration)});`);
    L.push(`    ${cvv} = 1;`);
    L.push(`  }`);
  } else if (ly.type === "text") {
    const size = fontPx(ly.font);
    const col = colorArr(ly.color, [1, 1, 1]);
    L.push(`  var ${v} = ${cv}.layers.addText("${esc(ly.text ?? "")}");`);
    L.push(`  try {`);
    L.push(`    var td = ${v}.property("ADBE Text Properties").property("ADBE Text Document");`);
    L.push(`    var tdv = td.value;`);
    L.push(`    tdv.fontSize = ${Math.round(size)};`);
    L.push(`    tdv.fillColor = [${col.join(",")}];`);
    L.push(`    tdv.justification = ParagraphJustification.CENTER_JUSTIFY;`);
    L.push(`    td.setValue(tdv);`);
    L.push(`  } catch (e) {}`);
  } else if (ly.type === "shape") {
    // 形状层：占位用固态（rect 语义等价；ellipse 记 TODO）
    const col = colorArr(ly.fill, [0.2, 0.33, 0.67]);
    const w = Math.max(2, Math.round(num(ly.w, 400)));
    const h = Math.max(2, Math.round(num(ly.h, 400)));
    if (ly.shape === "ellipse") L.push(`  // TODO: 原层为椭圆形状,固态占位,可手动换 shape layer`);
    L.push(`  var ${v} = ${cv}.layers.addSolid([${col.join(",")}], "${name}", ${w}, ${h}, 1, ${r3(c.duration)});`);
  } else {
    // image / video / null / 未知 → 灰色固态占位
    const w = Math.max(2, Math.round(num(ly.w, c.w)));
    const h = Math.max(2, Math.round(num(ly.h, c.h)));
    L.push(`  // 占位素材(${esc(String(ly.type))}${ly.asset ? ` asset=${esc(String(ly.asset))}` : ""}): 请替换为真实素材`);
    L.push(`  var ${v} = ${cv}.layers.addSolid([0.35,0.35,0.4], "${name} [占位]", ${w}, ${h}, 1, ${r3(c.duration)});`);
  }

  L.push(`  ${v}.name = "${name}";`);
  L.push(`  ${v}.inPoint = ${r3(inn)}; ${v}.outPoint = ${r3(out)};`);
  if (parentNullVar) L.push(`  try { ${v}.parent = ${parentNullVar}; } catch (e) {}`);
  if (ly.blend && ly.blend !== "normal") {
    L.push(`  // 混合模式: ${esc(ly.blend)}`);
    const bm = BLEND_JSX[ly.blend];
    if (bm) L.push(`  try { ${v}.blendingMode = BlendingMode.${bm}; } catch (e) {}`);
  }

  const tf = `${v}.property("ADBE Transform Group")`;
  L.push(`  ${tf}.property("ADBE Position").setValue([${r3(px)}, ${r3(py)}]);`);

  const anim = ly.anim ?? {};
  // 烘焙开且该层有时序算子命中的属性 → 由 emitBakedOps 合并发射，此处跳过对应基轨
  const bakedProps = new Set(ctx.bakeOps ? bakeLayerOps(ly).tracks.map((t) => t.prop) : []);

  // position（x/y 双轨合并，值=画布绝对 px）
  if ((anim.x?.length || anim.y?.length) && !bakedProps.has("position")) {
    emitKeys(ctx, `${tf}.property("ADBE Position")`, positionBaseKeys(anim, [px, py]));
  }
  // scale（scale 统一 / sx,sy 分轨；AE 百分数；footage 乘 cover）
  if (!bakedProps.has("scale")) {
    const scKeys = scaleBaseKeys(anim, coverExpr);
    if (scKeys.length) emitKeys(ctx, `${tf}.property("ADBE Scale")`, scKeys);
    else if (coverExpr) {
      // footage 无缩放动画 → 静态 cover 缩放充满 slot
      L.push(`  ${tf}.property("ADBE Scale").setValue([100*${coverExpr}, 100*${coverExpr}]);`);
    }
  }
  // rotation（度）
  if (anim.rot?.length && !bakedProps.has("rotation")) {
    emitKeys(
      ctx,
      `${tf}.property("ADBE Rotate Z")`,
      anim.rot.map((k) => ({ t: k.t, value: `${r3(num(k.v, 0))}`, e: k.e })),
    );
  }
  // opacity（IR [0,1] → AE %）
  if (anim.opacity?.length) {
    emitKeys(
      ctx,
      `${tf}.property("ADBE Opacity")`,
      anim.opacity.map((k) => ({ t: k.t, value: `${r3(Math.min(1, Math.max(0, num(k.v, 1))) * 100)}`, e: k.e })),
    );
  }
  if (anim.ls?.length) {
    L.push(`  // TODO: letterspacing 轨未自动映射（AE 需 Animator>Tracking），共 ${anim.ls.length} 帧`);
  }

  emitEffects(ctx, v, ly.fx);
  if (ctx.bakeOps) emitBakedOps(ctx, ly, v, tf, coverExpr);
  if (ly.raw_fx?.length) {
    L.push(`  // TODO 原工程还有未解析特效: ${esc(ly.raw_fx.join(", "))}`);
  }
}

/** 组动画：x/y 轨降到 null（偏移 = v - pos），其余通道注释说明 */
function emitGroupAnim(ctx: Ctx, v: string, ly: IRLayer): void {
  const anim = ly.anim ?? {};
  const px = num(ly.pos?.[0], 0);
  const py = num(ly.pos?.[1], 0);
  if (anim.x?.length || anim.y?.length) {
    const merged = mergeChannelTracks(anim.x, anim.y, px, py);
    emitKeys(
      ctx,
      `${v}.property("ADBE Transform Group").property("ADBE Position")`,
      merged.map((k) => ({ t: k.t, value: `[${r3(k.a - px)}, ${r3(k.b - py)}]`, e: k.e })),
    );
  }
  for (const ch of ["scale", "rot", "opacity"] as const) {
    if (anim[ch]?.length) {
      ctx.lines.push(`  // TODO: 组自身 ${ch} 动画未映射到 null（子层坐标为画布绝对值,直接缩放会偏移）`);
      ctx.warnings.push(`jsx: 组 ${ly.id} 的 ${ch} 动画需手动复现`);
    }
  }
}

const BLEND_JSX: Record<string, string> = {
  screen: "SCREEN",
  add: "ADD",
  multiply: "MULTIPLY",
  overlay: "OVERLAY",
  lighten: "LIGHTEN",
  darken: "DARKEN",
  "soft-light": "SOFT_LIGHT",
  "hard-light": "HARD_LIGHT",
  difference: "DIFFERENCE",
  exclude: "EXCLUSION",
  hue: "HUE",
  color: "COLOR",
};

/** 路径正斜杠化（footage import 用；纯字符串处理，不做 IO）。 */
function fwdSlash(p: string): string {
  return p.replace(/\\/g, "/");
}

/** footage import 注册段：每个唯一路径 importFile 一次、缓存到变量。写进 ctx.footageVars。 */
function emitFootageImports(ctx: Ctx, paths: string[]): void {
  const L = ctx.lines;
  const uniq = [...new Set(paths)];
  if (uniq.length === 0) return;
  L.push(`  // —— 素材导入（每素材仅导入一次、变量缓存复用）——`);
  let i = 0;
  for (const p of uniq) {
    const vn = `fg${++i}`;
    ctx.footageVars.set(p, vn);
    L.push(`  var ${vn} = null;`);
    L.push(
      `  try { ${vn} = app.project.importFile(new ImportOptions(new File("${esc(fwdSlash(p))}"))); } catch (e) { ${vn} = null; }`,
    );
  }
}

/** 建一个 Ctx。 */
function newCtx(opts: JsxOpts | undefined): Ctx {
  return {
    lines: [],
    warnings: [],
    layerSeq: 0,
    compVar: opts?.compVar ?? "comp",
    footage: opts?.footage ?? {},
    bakeOps: !!opts?.bakeOps,
    footageVars: new Map(),
  };
}

/** IR → ExtendScript 文本 */
export function irToJsx(ir: IRProject, opts?: JsxOpts): { jsx: string; warnings: string[] } {
  const c = ir.canvas;
  const ctx = newCtx(opts);
  const compName = esc(ir.id || "ir-comp");
  const bg = colorArr(c.bg, [0.04, 0.04, 0.07]);
  const w = Math.max(4, Math.round(num(c.w, 1920)));
  const h = Math.max(4, Math.round(num(c.h, 1080)));
  const fps = Math.min(99, Math.max(1, num(c.fps, 30)));
  const dur = Math.max(0.1, num(c.duration, 3));

  const L = ctx.lines;
  L.push(opts?.header ?? HEADER);
  L.push(`// 源: ${esc(String(ir.source ?? ir.id ?? ""))}`);
  L.push(``);
  L.push(`app.beginUndoGroup("IR Rebuild ${compName}");`);
  L.push(`(function () {`);
  L.push(`  var comp = app.project.items.addComp("${compName}", ${w}, ${h}, 1, ${r3(dur)}, ${r3(fps)});`);
  L.push(`  try { comp.bgColor = [${bg.join(",")}]; } catch (e) {}`);

  // footage 导入（有素材注入映射时）
  if (opts?.footage && Object.keys(opts.footage).length) {
    emitFootageImports(
      ctx,
      Object.values(opts.footage).map((f) => f.path),
    );
  }

  // IR 绘制序：第一个在最底。AE addLayer 每次压到最上 → 顺序遍历即天然吻合（后加的在上）。
  for (const ly of ir.layers ?? []) emitLayer(ctx, ir, ly, null);

  L.push(``);
  L.push(`  comp.openInViewer();`);
  L.push(`})();`);
  L.push(`app.endUndoGroup();`);
  return { jsx: L.join("\n") + "\n", warnings: ctx.warnings };
}

export function exportJsx(ir: IRProject): ExportResult {
  const { jsx, warnings } = irToJsx(ir);
  return {
    filename: `${ir.id || "ir"}.jsx`,
    mime: "application/javascript",
    data: jsx,
    warnings,
  };
}

// ---------------------------------------------------------------- MAD 母合成拼接（D6）

/** 一个技法窗口：完整工程 IR + 裁窗 + 素材注入 + 母时间线落点。 */
export interface MadWindow {
  /** 完整工程 IR（关键帧原样全铺、零裁剪）。 */
  ir: IRProject;
  /** 子合成命名唯一化后缀源（uid，与 seq 合成唯一名）。 */
  uid: string;
  /** 窗口序号（0-based）。 */
  seq: number;
  /** 源工程时间线上的窗口起点（秒）。 */
  t0: number;
  /** 源工程时间线上的窗口终点（秒）。 */
  t1: number;
  /** 母时间线落点（秒）。 */
  dropAt: number;
  /** 母时间线上该窗口展示时长（秒；beat 量化只裁短不拉长，缺省=t1−t0）。 */
  outLen?: number;
  /** 素材注入：本窗口各 slot layerId → footage（同一素材、各 srcOffset 错开）。 */
  footage?: FootageMap;
}

/** beat marker：时刻（母时间线秒）+ 是否 downbeat。 */
export interface BeatMarker {
  t: number;
  downbeat: boolean;
}

export interface MadJsxOpts {
  /** 母合成画布。 */
  master: { w: number; h: number; fps: number; name?: string };
  /** 技法窗口序列。 */
  windows: MadWindow[];
  /** 产物 header（默认产品定稿口径由调用侧注入）。 */
  header?: string;
  /** BGM：入母合成音轨 + beat marker。 */
  bgm?: { path: string; markers?: BeatMarker[] };
}

/**
 * MAD 母合成拼接：footage 一次导入（跨子合成共享）→ 每窗口建子合成（完整 IR 全铺 + 素材注入 + 烘焙）
 * → 母合成三属性裁窗串接 + BGM 入轨 + beat marker。产单一 .jsx。
 */
export function madJsx(opts: MadJsxOpts): { jsx: string; warnings: string[] } {
  const { master, windows } = opts;
  const mw = Math.max(4, Math.round(master.w));
  const mh = Math.max(4, Math.round(master.h));
  const mfps = Math.min(99, Math.max(1, master.fps || 30));
  const masterName = esc(master.name ?? "MAD Master");

  // 全局 footage 路径（跨窗口去重、母合成级仅导入一次）
  const allPaths: string[] = [];
  for (const win of windows) {
    for (const f of Object.values(win.footage ?? {})) allPaths.push(f.path);
  }

  const ctx = newCtx({ bakeOps: true });
  const L = ctx.lines;
  L.push(opts.header ?? HEADER);
  L.push(``);
  L.push(`app.beginUndoGroup("MAD Rebuild ${masterName}");`);
  L.push(`(function () {`);

  // footage 导入（母合成级共享）
  emitFootageImports(ctx, allPaths);
  const globalFootageVars = ctx.footageVars;

  // 母合成末窗切点 → 母合成时长
  let totalDur = 0.1;
  for (const win of windows) {
    const len = win.outLen ?? win.t1 - win.t0;
    totalDur = Math.max(totalDur, win.dropAt + Math.max(0.01, len));
  }
  L.push(``);
  L.push(`  var master = app.project.items.addComp("${masterName}", ${mw}, ${mh}, 1, ${r3(totalDur)}, ${r3(mfps)});`);
  L.push(`  try { master.bgColor = [0.04,0.04,0.07]; } catch (e) {}`);

  // 逐窗口：建子合成 + 发射层体
  const subVars: { subVar: string; win: MadWindow }[] = [];
  windows.forEach((win, wi) => {
    const c = win.ir.canvas;
    const sw = Math.max(4, Math.round(num(c.w, 1920)));
    const sh = Math.max(4, Math.round(num(c.h, 1080)));
    const sfps = Math.min(99, Math.max(1, num(c.fps, 30)));
    const sdur = Math.max(0.1, num(c.duration, 3));
    const subName = esc(`${win.uid}-${win.seq}`); // 唯一命名（uid+序号）
    const subVar = `sub${wi}`;
    L.push(``);
    L.push(`  // ==== 子合成 #${wi} 技法 ${subName}（源窗 t0=${r3(win.t0)} t1=${r3(win.t1)}）====`);
    L.push(`  var ${subVar} = app.project.items.addComp("${subName}", ${sw}, ${sh}, 1, ${r3(sdur)}, ${r3(sfps)});`);

    // 该窗口 footage 映射（layerId → 全局 footage 变量已注册）
    const winFootage: FootageMap = { ...(win.footage ?? {}) };
    const subCtx: Ctx = {
      lines: L,
      warnings: ctx.warnings,
      layerSeq: 0,
      compVar: subVar,
      footage: winFootage,
      bakeOps: true,
      footageVars: globalFootageVars,
    };
    for (const ly of win.ir.layers ?? []) emitLayer(subCtx, win.ir, ly, null);
    subVars.push({ subVar, win });
  });

  // 母合成三属性裁窗串接
  L.push(``);
  L.push(`  // ==== 母合成裁窗串接（startTime=落点−t0，inPoint=落点，outPoint=落点+窗长）====`);
  subVars.forEach(({ subVar, win }, wi) => {
    const len = Math.max(0.01, win.outLen ?? win.t1 - win.t0);
    const lv = `mL${wi}`;
    L.push(`  var ${lv} = master.layers.add(${subVar});`);
    L.push(`  ${lv}.startTime = ${r3(win.dropAt - win.t0)};`);
    L.push(`  ${lv}.inPoint = ${r3(win.dropAt)};`);
    L.push(`  ${lv}.outPoint = ${r3(win.dropAt + len)};`);
    // 跨尺寸/fps cover 缩放（子合成尺寸 ≠ 母合成 → 充满母画布无黑边）
    L.push(`  try {`);
    L.push(`    var _cov = Math.max(${mw} / ${subVar}.width, ${mh} / ${subVar}.height) * 100;`);
    L.push(`    ${lv}.property("ADBE Transform Group").property("ADBE Scale").setValue([_cov, _cov]);`);
    L.push(`    ${lv}.property("ADBE Transform Group").property("ADBE Position").setValue([${mw / 2}, ${mh / 2}]);`);
    L.push(`  } catch (e) {}`);
  });

  // BGM 入母合成音轨 + beat marker
  if (opts.bgm) {
    L.push(``);
    L.push(`  // ==== BGM 入轨（importFile 包 try/catch，AE 侧文件缺失/损坏脚本继续跑完仅缺音轨）====`);
    L.push(`  try {`);
    L.push(`    var bgm = app.project.importFile(new ImportOptions(new File("${esc(fwdSlash(opts.bgm.path))}")));`);
    L.push(`    var bgmL = master.layers.add(bgm);`);
    L.push(`    bgmL.startTime = 0;`);
    L.push(`  } catch (e) {}`);
    const markers = opts.bgm.markers ?? [];
    if (markers.length) {
      L.push(`  // beat marker（downbeat 带标签区分）`);
      L.push(`  try {`);
      L.push(`    var mk = master.property("ADBE Marker");`);
      for (const m of markers) {
        const label = m.downbeat ? "downbeat" : "beat";
        L.push(`    mk.setValueAtTime(${r3(m.t)}, new MarkerValue("${label}"));`);
      }
      L.push(`  } catch (e) {}`);
    }
  }

  L.push(``);
  L.push(`  master.openInViewer();`);
  L.push(`})();`);
  L.push(`app.endUndoGroup();`);
  return { jsx: L.join("\n") + "\n", warnings: ctx.warnings };
}
